######################################
# Maven Build Info
# Creator: com.tauasa.maven.mojo.MavenBuildInfoMojo
# Date: Sat Apr 30 02:09:15 PDT 2011
######################################

build.name=teamsac-public
build.artifact=teamsac-public
build.version=1.1
build.number=1104300209
build.os=Windows 7 [6.1] - x86
build.jvm=Sun Microsystems Inc. 1.5.0_22 [class version: 49.0]
build.user=ttimoteo
build.scm.vendor=https://free2.projectlocker.com/tauasa/teamsac/svn/teamsac-public
build.ci.vendor=Unspecified
